# config/__init__.py
# DeepAiUG v1.8.0 - Modulo configurazione
# ============================================================================

from .constants import (
    # Versione
    VERSION,
    VERSION_STRING,
    VERSION_DESCRIPTION,
    # Paths
    BASE_DIR,
    CONVERSATIONS_DIR,
    KNOWLEDGE_BASE_DIR,
    WIKI_CACHE_DIR,
    SECRETS_DIR,
    WIKI_CONFIG_FILE,
    WIKI_CONFIG_ALT,
    # Defaults
    DEFAULT_MAX_MESSAGES,
    DEFAULT_MAX_TOKENS_ESTIMATE,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_CHUNK_OVERLAP,
    DEFAULT_TOP_K_RESULTS,
    # Formati
    SUPPORTED_EXTENSIONS,
    EXPORT_FORMATS,
    CONTENT_OPTIONS,
    # UI
    USER_MESSAGE_COLOR,
    ASSISTANT_MESSAGE_COLOR,
    USER_MESSAGE_COLOR_DARK,
    ASSISTANT_MESSAGE_COLOR_DARK,
    # Providers
    CLOUD_PROVIDERS,
    # MediaWiki
    MEDIAWIKI_DEFAULT_USER_AGENT,
    MEDIAWIKI_DEFAULT_REQUEST_DELAY,
    MEDIAWIKI_DEFAULT_BATCH_SIZE,
    MEDIAWIKI_DEFAULT_TIMEOUT,
    # Wiki Types
    WIKI_TYPES,
    # v1.5.0 - File Upload
    ALLOWED_UPLOAD_TYPES,
    VISION_MODEL_PATTERNS,
    MAX_FILE_SIZE_MB,
    MAX_DOCUMENT_CHARS,
    # v1.8.0 - Socratic Modes
    SOCRATIC_MODES,
    DEFAULT_SOCRATIC_MODE,
    # v1.10.0 - Session Map (F2)
    SESSION_MAP_MODES,
    DEFAULT_SESSION_MAP_MODE,
    SESSION_MAP_NUDGE_THRESHOLD,
    SESSION_MAP_PROGRESSIVE_VISIBLE_AFTER,
)

# v1.10.0 - Branding
from .branding import (
    APP_TITLE,
    APP_ICON,
    APP_SUBTITLE,
    NEWS_BANNER_ENABLED,
    NEWS_BANNER_TEXT,
    NEWS_BANNER_VERSION,
)

__all__ = [
    "VERSION",
    "VERSION_STRING",
    "VERSION_DESCRIPTION",
    "BASE_DIR",
    "CONVERSATIONS_DIR",
    "KNOWLEDGE_BASE_DIR",
    "WIKI_CACHE_DIR",
    "SECRETS_DIR",
    "WIKI_CONFIG_FILE",
    "WIKI_CONFIG_ALT",
    "DEFAULT_MAX_MESSAGES",
    "DEFAULT_MAX_TOKENS_ESTIMATE",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_CHUNK_OVERLAP",
    "DEFAULT_TOP_K_RESULTS",
    "SUPPORTED_EXTENSIONS",
    "EXPORT_FORMATS",
    "CONTENT_OPTIONS",
    "USER_MESSAGE_COLOR",
    "ASSISTANT_MESSAGE_COLOR",
    "USER_MESSAGE_COLOR_DARK",
    "ASSISTANT_MESSAGE_COLOR_DARK",
    "CLOUD_PROVIDERS",
    "MEDIAWIKI_DEFAULT_USER_AGENT",
    "MEDIAWIKI_DEFAULT_REQUEST_DELAY",
    "MEDIAWIKI_DEFAULT_BATCH_SIZE",
    "MEDIAWIKI_DEFAULT_TIMEOUT",
    "WIKI_TYPES",
    # v1.5.0 - File Upload
    "ALLOWED_UPLOAD_TYPES",
    "VISION_MODEL_PATTERNS",
    "MAX_FILE_SIZE_MB",
    "MAX_DOCUMENT_CHARS",
    # v1.8.0 - Socratic Modes
    "SOCRATIC_MODES",
    "DEFAULT_SOCRATIC_MODE",
    # v1.10.0 - Session Map (F2)
    "SESSION_MAP_MODES",
    "DEFAULT_SESSION_MAP_MODE",
    "SESSION_MAP_NUDGE_THRESHOLD",
    "SESSION_MAP_PROGRESSIVE_VISIBLE_AFTER",
    # v1.10.0 - Branding
    "APP_TITLE",
    "APP_ICON",
    "APP_SUBTITLE",
    "NEWS_BANNER_ENABLED",
    "NEWS_BANNER_TEXT",
    "NEWS_BANNER_VERSION",
]
